# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t1e',
            name='aut',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post1s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
