# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_t1e_aut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1e',
            name='author',
        ),
    ]
