# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_t1e_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t1e',
            options={'verbose_name': 'Test123'},
        ),
    ]
